version: '3.8'

services:
  db:
    image: mariadb:10.6.4-focal
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306

  wordpress:
    image: wordpress:latest   # Dockerfile + wp_config.sh
    container_name: wordpress
    ports:
      - "80:80"  # php-fpm port
    restart: always
    environment:
      # Database connection
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      # WordPress admin account
      - WP_ADMIN_USER=chahlaoui
      - WP_ADMIN_PASSWORD=pass@chah_123
      - WP_ADMIN_EMAIL=chahlaoui@gmail.com
      - DOMAIN_NAME=achahlaoui.42.fr
    depends_on:
      - db

volumes:
  db_data:
  wordpress_data:
