version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file: .env
    secrets:
      - db_user_pass
      - db_root_pass
    volumes:
      - $DB_VOLUME:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    secrets:
      - db_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - $WP_VOLUME:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - $WP_VOLUME:/var/www/html
    networks:
      - inception

# ========================
# NETWORK &&& SECRETS
# ========================
networks:
  inception:
    driver: bridge

secrets:
  db_root_pass:
    file: ../secrets/db_root_pass
  db_user_pass:
    file: ../secrets/db_user_pass
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  wp_user_pass:
    file: ../secrets/wp_user_pass