version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    secrets:
      - db_user_pass
      - db_root_pass
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    secrets:
      - db_user_pass
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ${WP_VOLUME}:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_user_pass:
    file: ../secrets/db_user_pass.txt
  db_root_pass:
    file: ../secrets/db_root_pass.txt
