version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password.txt
      - db_root_password.txt
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - db_password.txt
      - credentials.txt
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

secrets:
  db_password.txt:
    file: ../secrets/db_password.txt
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
  credentials.txt:
    file: ../secrets/credentials.txt

networks:
  inception:
    driver: bridge
