# FROM debian:bullseye

# RUN apt update && apt install mariadb-server  -y 

# RUN mkdir -p /var/lib/mysql && \
#     chown -R mysql:mysql /var/lib/mysql 

# COPY tools/entrypoint.sh /usr/bin/entrypoint.sh

# RUN chmod +x /usr/bin/entrypoint.sh

# ENTRYPOINT ["bash", "entrypoint.sh"]